### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#13]
As a User
I want to create events
so I have an overview of  the events I want attend

## AC
* Form with input fields: event name, date, location
*'Add'-Button that submits data in form
* Created events are shown as a list
* The form resets

##Design

##Tasks
- [x] Create new branch
- [x] create three input labels and input fields 
- [x] create submit button
- [ ] link with react routes

**Comment by JessicaLoers** [comment]
Hi @Han-90 ✌️
Please think about the following points 🙂
Think about the purpose of the user. What is the user's need? 

I'm unsure what kind of events you mean, but a Value Statement might look like this:

**As a User**
**I want** to create single music events
**So that I** have an overview of the events I want to attend. 

**AC** - The **acceptance criteria** from the user's point of view, e.g.

- Form with input fields: event name, date, location
- 'Add'-Button that submits data in form
- Created events are shown as a list
- The form resets
....

**Comment by Han-90** [comment]
thanks for your suggestions
