### ISSUE TITLE
Design for Navbar

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#17]
As a designer
I want to improve the UI of the navbar
so that the user has a better experience using the app

## AC 
* should based on the design
* svg for home and event button

## Tasks

- [ ] create new branch
- [ ] import svg files 
- [ ] edit styled components
