### ISSUE TITLE
Design for Header

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#19]
As a designer
I want to improve the UI of the header
so that the user has a better experience using the app

##AC
*should based on the design
*should be available on the homescreen

##Tasks
 
- [ ] create new branch
- [ ] import material ui
- [ ] edit styles of imported component
