### ISSUE TITLE
## Inspiration

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#3]
As a User 
I want to get inspiration
So I know which song I will play next

## AC

* Homescreen with random music titles or music sheets for inspiration
* List of music titles on home screen
* titles should include lyrics and music sheets as an image

## Design
![Untitled-2022-06-15-2118](https://user-images.githubusercontent.com/98271167/174800635-b28b329b-e5f9-4055-a284-f5126a19a6f5.png)

## Tasks

- [ ] create new branch
- [ ] create component inspiration with song title, interpret, genre
- [ ] render the list of song titles

**Comment by JessicaLoers** [comment]
Well, done 👍

Just one comment: 
- Please add the **Complexity** of your feature. Rate in T-Shirt sizes: XS, S, M, L, XL
