### ISSUE TITLE
postponed Add Navbar 

### ISSUE THREAD

**Issue by Han-90** [Han-90/capstone-project#7]
As a user
I want to have a navbar
So I can easily navigate between different pages

## AC
* create navbar
* navbar should be accessible from every page
* should be on the bottom of each page
* should navigate to the different features e.g.(Events, inspiration, home)

## Design
![Untitled-2022-06-15-2118](https://user-images.githubusercontent.com/98271167/174804385-a544c455-5155-4f59-b9ca-d50167682ff1.png)

## Tasks

- [ ] create a new branch
- [ ] create a navbar component
- [ ] implement react router
- [ ] create routes to the different pages
